-- SKEMA SQL UNTUK SUPABASE
-- Salin dan jalankan script ini di SQL Editor Supabase Anda untuk membuat tabel & memuat data awal.

-- Hapus tabel lama jika ada
DROP TABLE IF EXISTS laporan_kinerjas;
DROP TABLE IF EXISTS laporan_visuals;
DROP TABLE IF EXISTS daerah_irigasis;
DROP TABLE IF EXISTS users;

-- 1. Tabel daerah_irigasis
CREATE TABLE daerah_irigasis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    kabupaten_kota VARCHAR(255),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    adm4_code VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tabel users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL, -- Di produksi disarankan menggunakan hash, di demo/prototype menggunakan plaintext/hash sederhana
    nip VARCHAR(255) UNIQUE,
    jabatan VARCHAR(255),
    wilayah_di VARCHAR(255),
    role VARCHAR(50) DEFAULT 'petugas',
    force_password_change BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Tabel laporan_visuals
CREATE TABLE laporan_visuals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daerah_irigasi_id BIGINT REFERENCES daerah_irigasis(id) ON DELETE CASCADE,
    petugas_nama VARCHAR(255),
    jenis_kegiatan VARCHAR(255) NOT NULL,
    deskripsi_kegiatan TEXT,
    video_path VARCHAR(1000) NOT NULL, -- Menyimpan URL video di Supabase Storage / R2
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Tabel laporan_kinerjas
CREATE TABLE laporan_kinerjas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    petugas_nama VARCHAR(255) NOT NULL,
    nip VARCHAR(255),
    jabatan VARCHAR(255),
    wilayah VARCHAR(255),
    atasan_nama VARCHAR(255),
    atasan_nip VARCHAR(255),
    atasan_jabatan VARCHAR(255),
    periode_bulan VARCHAR(50) NOT NULL,
    uraian_bulanan TEXT,
    data_aktivitas JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Seed Data Awal
INSERT INTO users (name, email, password, nip, role, jabatan, wilayah_di, force_password_change, is_active)
VALUES 
('Admin Sigasda', 'admin@sigasda.com', 'admin123', '199001012020011001', 'admin', 'Kepala Bidang', 'Seluruh Wilayah', FALSE, TRUE),
('Ahmad Dani', 'petugas@sigasda.com', 'petugas123', '199402282023051001', 'petugas', 'PPA', 'Primer Kolondom', FALSE, TRUE);

INSERT INTO daerah_irigasis (nama, kabupaten_kota, latitude, longitude)
VALUES 
('Primer Kolondom', 'Palu', -0.9022, 119.8732),
('Gumbasa', 'Sigi', -1.0254, 119.9241),
('Singkoyo', 'Banggai', -1.2584, 121.3458);

-- 6. Aktifkan RLS dan bypass dengan service role key atau atur kebijakan akses publik untuk keperluan demo/testing
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE daerah_irigasis ENABLE ROW LEVEL SECURITY;
ALTER TABLE laporan_visuals ENABLE ROW LEVEL SECURITY;
ALTER TABLE laporan_kinerjas ENABLE ROW LEVEL SECURITY;

-- Buat policy akses penuh untuk mempermudah demo
CREATE POLICY "Akses Publik Penuh Users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Akses Publik Penuh DI" ON daerah_irigasis FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Akses Publik Penuh Visual" ON laporan_visuals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Akses Publik Penuh Kinerja" ON laporan_kinerjas FOR ALL USING (true) WITH CHECK (true);
